// 100 Days of Modern AI — full curriculum data (2026 edition)
// Phases: raw-API foundations → evals → context & cost → agents → MCP → retrieval → security → capstone.
// Every 7th day is a Rest + Recap + Showcase day.

import type {
  Challenge,
  Course,
  DayPlan,
  Project,
  QuizQuestion,
  WeekPlan,
} from "./types";

export const WEEKS: WeekPlan[] = [
  { week: 1, title: "Foundations from scratch", start: 1, end: 7 },
  { week: 2, title: "Evals begin: error analysis", start: 8, end: 14 },
  { week: 3, title: "Evals into CI, golden datasets, RAG eval", start: 15, end: 21 },
  { week: 4, title: "Context engineering + cost begin", start: 22, end: 28 },
  { week: 5, title: "Memory, structured output, finish P3", start: 29, end: 35 },
  { week: 6, title: "Agents from scratch", start: 36, end: 42 },
  { week: 7, title: "Agent patterns & orchestration", start: 43, end: 49 },
  { week: 8, title: "Long-horizon agents & harnesses", start: 50, end: 56 },
  { week: 9, title: "Buffer, tasters, mid-challenge case study", start: 57, end: 63 },
  { week: 10, title: "Build an MCP server", start: 64, end: 70 },
  { week: 11, title: "Retrieval depth", start: 71, end: 77 },
  { week: 12, title: "AI security & red-teaming", start: 78, end: 84 },
  { week: 13, title: "Guardrails, defense, ship P8", start: 85, end: 91 },
  { week: 14, title: "Capstone + client-acquisition sprint", start: 92, end: 100 },
];

export const PROJECTS: Project[] = [
  {
    id: "P1",
    name: "Hand-rolled RAG Q&A",
    short: "RAG Q&A",
    blurb: "RAG over your own docs — no framework, fully traced.",
    start: 1,
    end: 7,
    shipDay: 7,
    description:
      "RAG over local docs with your own chunking, embeddings, FAISS/Chroma store, retrieve + generate, served via FastAPI with Phoenix tracing — no RAG framework.",
    doneWhen:
      "A user asks a question over their own documents and gets a grounded, cited answer, and every call is traceable.",
  },
  {
    id: "P2",
    name: "Eval harness + aligned judge",
    short: "Eval harness",
    blurb: "Error analysis → LLM judge aligned to you → CI gate.",
    start: 8,
    end: 21,
    shipDay: 21,
    flagship: true,
    description:
      "Trace collection → error analysis → named failure taxonomy → code-based + LLM-as-judge evals → judge aligned to human labels (Cohen's Kappa) → golden dataset → promptfoo/Ragas in a CI regression gate.",
    doneWhen:
      "A PR that degrades quality fails CI automatically, and the judge agrees with your labels on a held-out set.",
  },
  {
    id: "P3",
    name: "AI Reliability & Cost Audit",
    short: "Cost audit",
    blurb: "Cut real cost, prove quality — the productized audit.",
    start: 22,
    end: 35,
    shipDay: 35,
    description:
      "Applied to your own P1 system: context audit, prompt caching, compaction, model routing, cost/latency dashboard, plus a repeatable audit checklist — the productized-service spec.",
    doneWhen:
      "A public case study reports a real % cost reduction and a measured quality delta, with a reusable checklist.",
  },
  {
    id: "P4",
    name: "Agent from scratch w/ tools",
    short: "Agent",
    blurb: "A while-loop agent with sharp, namespaced tools.",
    start: 36,
    end: 42,
    shipDay: 42,
    description:
      "A while-loop think→act→observe agent, no framework, 3+ well-designed namespaced tools, error handling, and its own eval suite.",
    doneWhen:
      "The agent reliably solves tasks needing its tools and passes trajectory + final-answer evals.",
  },
  {
    id: "P5",
    name: "Long-horizon agent + harness",
    short: "Harness",
    blurb: "Durable state, self-verification, resumes after restarts.",
    start: 50,
    end: 56,
    shipDay: 56,
    description:
      "Durable external state, self-verification (doer-verifier), reflection, context-awareness + compaction under a hard cost cap.",
    doneWhen:
      "The agent resumes a multi-session task after a “restart” and completes it within budget.",
  },
  {
    id: "P6",
    name: "MCP server over hand-built DB",
    short: "MCP server",
    blurb: "Your SQLite DB, exposed to real clients via MCP.",
    start: 64,
    end: 70,
    shipDay: 70,
    description:
      "A real seeded SQLite DB exposed via an MCP server (tools + resources + prompts), namespaced, connected to a real MCP client like Claude Desktop, with tool-use evals.",
    doneWhen:
      "A real client drives your database through MCP and tool-selection accuracy is measured.",
  },
  {
    id: "P7",
    name: "Hybrid-search retrieval engine",
    short: "Retrieval",
    blurb: "BM25 + vectors + rerank, measured properly.",
    start: 71,
    end: 77,
    shipDay: 77,
    description:
      "BM25 + vectors fused with RRF, query rewriting/HyDE, reranking, contextual chunks, evaluated with recall@k / MRR / context-precision.",
    doneWhen:
      "Hybrid + rerank measurably beats naive vector search on your golden queries.",
  },
  {
    id: "P8",
    name: "Red-team + guardrails kit",
    short: "Red-team",
    blurb: "Attack your own apps, then block every exploit.",
    start: 78,
    end: 89,
    shipDay: 89,
    description:
      "OWASP LLM + Agentic threat models, attacks via garak/promptfoo/PyRIT (incl. multi-turn crescendo), then input/output guardrails, least-privilege tool scopes, and security regression tests in CI.",
    doneWhen:
      "The guardrails block your own documented attacks and the security suite stays green in CI.",
  },
  {
    id: "CAP",
    name: "Final capstone",
    short: "Capstone",
    blurb: "Retrieval + agent + evals + security in one system.",
    start: 90,
    end: 100,
    shipDay: 100,
    description:
      "One polished system combining retrieval + agent + evals + security, with a full case study — plus the client-acquisition sprint (portfolio, repositioning, productized audit offer).",
    doneWhen:
      "It passes its own evals, survives its own red-team, and ships with a public case study and metrics.",
  },
];

/** External courses referenced across the curriculum's day resources. */
export const COURSES: Course[] = [
  {
    id: "hf-agents-course",
    name: "Agents Course",
    provider: "Hugging Face",
    url: "https://huggingface.co/learn/agents-course",
    blurb: "Free course on building agents — smolagents and LangGraph units.",
    days: [48],
  },
  {
    id: "hf-mcp-course",
    name: "MCP Course",
    provider: "Hugging Face",
    url: "https://huggingface.co/learn/mcp-course",
    blurb: "Build MCP servers and clients across three hands-on units.",
    days: [61, 62, 65, 66, 68],
  },
  {
    id: "dlai-advanced-rag",
    name: "Building and Evaluating Advanced RAG",
    provider: "DeepLearning.AI",
    url: "https://www.deeplearning.ai/short-courses/building-evaluating-advanced-rag/",
    blurb: "The RAG triad — context relevance, groundedness, answer relevance.",
    days: [17],
  },
  {
    id: "dlai-eval-agents",
    name: "Evaluating AI Agents",
    provider: "DeepLearning.AI",
    url: "https://www.deeplearning.ai/short-courses/evaluating-ai-agents/",
    blurb: "Arize AI on tracing and evaluating agent behavior.",
    days: [19, 41],
  },
  {
    id: "dlai-improving-accuracy",
    name: "Improving Accuracy of LLM Applications",
    provider: "DeepLearning.AI",
    url: "https://www.deeplearning.ai/short-courses/improving-accuracy-of-llm-applications/",
    blurb: "AMD/Meta techniques for pushing LLM app accuracy higher.",
    days: [32],
  },
  {
    id: "dlai-computer-use",
    name: "Building Toward Computer Use with Anthropic",
    provider: "DeepLearning.AI",
    url: "https://www.deeplearning.ai/short-courses/building-toward-computer-use-with-anthropic/",
    blurb: "How Claude's computer-use capability was built, from Anthropic.",
    days: [57],
  },
  {
    id: "dlai-voice-agents",
    name: "Voice for AI Agents and Applications",
    provider: "DeepLearning.AI",
    url: "https://www.deeplearning.ai/short-courses/voice-for-ai-agents-and-applications/",
    blurb: "Vocal Bridge — adding voice interfaces to agentic apps.",
    days: [58],
  },
  {
    id: "dlai-mcp-rich-context",
    name: "MCP: Build Rich-Context AI Apps with Anthropic",
    provider: "DeepLearning.AI",
    url: "https://www.deeplearning.ai/short-courses/mcp-build-rich-context-ai-apps-with-anthropic/",
    blurb: "Anthropic's own course on building rich-context apps with MCP.",
    days: [62],
  },
  {
    id: "dlai-rag",
    name: "Retrieval Augmented Generation (RAG)",
    provider: "DeepLearning.AI",
    url: "https://www.deeplearning.ai/short-courses/retrieval-augmented-generation-rag/",
    blurb: "Search techniques that make retrieval actually work.",
    days: [71],
  },
  {
    id: "dlai-red-teaming",
    name: "Red Teaming LLM Applications",
    provider: "DeepLearning.AI",
    url: "https://www.deeplearning.ai/short-courses/red-teaming-llm-applications/",
    blurb: "Giskard on finding and fixing LLM app vulnerabilities.",
    days: [79],
  },
];

/** The public cohort's shared Day-1 date ("Align with cohort" in onboarding). */
const COHORT_START_DATE = "2026-06-01";

/** Monorepo with one folder per day — name folders day-1, day-2, … day-100. */
const GITHUB_REPO = "https://github.com/ahmad19sep/100-days-learning-ai";

/**
 * Daily lesson videos — the owner's one-line-a-day job.
 *
 * When a day's video is live, add its link here and deploy:
 *
 *   1: "https://youtu.be/XXXXXXXXXXX",
 *   2: "https://www.youtube.com/watch?v=YYYYYYYYYYY",
 *
 * That day's page then embeds the player, and the dashboard "Watch"
 * button opens it. Days without a link keep the "coming soon" slot.
 */
const VIDEOS: Record<number, string> = {
  // 1: "https://youtu.be/XXXXXXXXXXX",
};

/**
 * Owner notes — a short message from you shown on that day's page
 * ("From @aixahmad" card). Add lines as the challenge runs:
 *
 *   14: "Common mistake today: don't skip the Kappa step — it's the whole point.",
 */
const OWNER_NOTES: Record<number, string> = {
  // 1: "Welcome to Day 1! Go slow, read the raw JSON, it pays off all 100 days.",
};

/**
 * Curated watch links per day — your video plus/or other creators' videos,
 * shown as clickable links in the day's resource card:
 *
 *   2: [{ label: "Karpathy — Let's build the GPT Tokenizer", url: "https://youtu.be/zduSFxRajkE" }],
 */
const WATCH_LINKS: Record<number, { label: string; url: string }[]> = {
  // 1: [{ label: "…", url: "https://…" }],
};

/**
 * Daily quiz — one multiple-choice check per day, graded instantly on
 * submit. Add a day's questions and deploy:
 *
 *   1: [{
 *     question: "What does the `usage` field on an API response tell you?",
 *     options: ["The model's temperature", "Token counts & cost", "The system prompt", "Rate limit remaining"],
 *     correctIndex: 1,
 *   }],
 *
 * Answers are never stored as "correct/incorrect" — they're re-graded
 * against this file every time, so fixing a typo in `correctIndex` fixes
 * everyone's score retroactively.
 */
const QUIZZES: Record<number, QuizQuestion[]> = {
  // 1: [{ question: "…", options: ["…", "…"], correctIndex: 0 }],
};

const CREATOR = {
  name: "Ahmad · AI Radar",
  handle: "@aixahmad",
  tagline: "teaching modern AI, in public",
};

function d(
  day: number,
  title: string,
  about: string,
  resource: string,
  build: string,
  extra: Partial<
    Omit<DayPlan, "day" | "title" | "about" | "resource" | "build">
  > = {}
): DayPlan {
  return {
    day,
    title,
    about,
    resource,
    build,
    projects: [],
    isRest: false,
    ...extra,
  };
}

const REST = "Rest + Recap + Showcase";
const REST_ABOUT =
  "No new topic today — every 7th day is a rest day. Recap the week, polish your repo, and show your work to the community. Rest days count toward your streak.";

export const DAYS: DayPlan[] = [
  // ── Week 1 — Foundations from scratch (P1) ──────────────────────────────
  d(1, "Call an LLM API directly — no SDK",
    "Every AI app is, at its core, one HTTP request to a model. Today you send that request by hand — the messages array, the model name, and the usage field that tells you exactly what every call costs.",
    "Anthropic Messages API docs + OpenAI chat completions reference",
    "Call Claude/OpenAI with raw httpx; print tokens & cost from the usage field",
    { projects: ["P1"], search: "call LLM API with python requests no SDK" }),
  d(2, "Tokenization — how models read text",
    "Models never see words; they see tokens. Understanding how text gets split (BPE) explains why calls cost what they cost, why models misspell, and why Urdu uses more tokens than English.",
    "Karpathy “Let's build the GPT Tokenizer” (video + fast.ai text version) + tiktokenizer web app",
    "Implement a mini BPE: get_stats + merge on a text file; compare token counts EN vs Urdu",
    { projects: ["P1"], search: "Karpathy let's build the GPT tokenizer BPE" }),
  d(3, "Embeddings — meaning as numbers",
    "An embedding turns a sentence into a list of numbers where similar meanings land close together. It's the engine behind semantic search and RAG — today you compute similarity yourself, no library magic.",
    "Microsoft Learn “Develop a RAG Solution — Generate Embeddings”",
    "Embed 20 sentences; compute cosine similarity by hand (numpy); rank nearest neighbors",
    { projects: ["P1"], search: "text embeddings explained cosine similarity" }),
  d(4, "Chunking documents the right way",
    "Before you can search documents, you must split them — and how you split decides what retrieval can ever find. You'll build three chunking strategies and see the trade-offs yourself.",
    "Anthropic “Contextual Retrieval” + pguso/rag-from-scratch chunking module",
    "Write 3 chunkers (fixed, sentence-window, overlap); measure chunk counts",
    { projects: ["P1"], search: "RAG chunking strategies explained" }),
  d(5, "Build the full RAG pipeline by hand",
    "RAG = fetch the right passages, then let the model answer from them. Today you connect the whole chain — ingest → chunk → embed → store → retrieve → generate — with plain Python, so no step is a black box.",
    "langchain-ai/rag-from-scratch notebooks (concepts) + KDnuggets “7 Steps to Build a Simple RAG”",
    "Wire ingest→chunk→embed→store (FAISS/Chroma)→retrieve→generate, no RAG framework",
    { projects: ["P1"], search: "build RAG from scratch python no framework" }),
  d(6, "Serve it as an API, with tracing",
    "A notebook isn't a product. You'll wrap your RAG loop in a real /ask endpoint and add tracing, so you can open any request later and see every step it took — the habit that powers everything in week 2+.",
    "FastAPI “First Steps” + Arize Phoenix tracing quickstart",
    "Wrap the RAG loop in a FastAPI /ask endpoint; add Phoenix/OpenInference tracing",
    { projects: ["P1"], search: "FastAPI tutorial LLM app Phoenix tracing" }),
  d(7, REST, REST_ABOUT,
    "Re-read your week's READMEs",
    "Polish P1 repo README; post demo GIF; review 2 viewers' repos on Discord",
    { projects: ["P1"], isRest: true }),

  // ── Week 2 — Evals begin: error analysis (P2) ───────────────────────────
  d(8, "Evals — why measuring quality is the real skill",
    "Anyone can demo an AI app; few can prove it works. Evals are how you measure quality so you can improve it. Step one: collect real traces (actual questions + answers) from your own RAG.",
    "Hamel Husain “LLM Evals: Everything You Need to Know” (evals-faq)",
    "Collect 30–50 real traces from your P1 RAG into a JSONL dataset",
    { doneWhen: "You have a trace dataset ready to analyze", videoTitle: "Day 8: Evals — yehi hai asli hunar", projects: ["P2"], search: "LLM evals introduction Hamel Husain" }),
  d(9, "Error analysis — read your app's answers",
    "The highest-value hour in AI engineering: read your app's real outputs one by one, like a human, and write down the first thing wrong with each. No tools, just careful looking.",
    "Hamel & Shreya lesson notes: error analysis, open/axial coding",
    "Hand-label your 50 traces; write open-ended failure notes on the FIRST failure per trace",
    { doneWhen: "50 traces labeled with free-text failure notes", videoTitle: "Day 9: Error analysis — insaan ki tarah dekho", projects: ["P2"], search: "LLM error analysis open coding traces" }),
  d(10, "Group failures into named categories",
    "Fifty messy notes become 5–8 named failure modes (e.g. “wrong chunk retrieved”, “ignored the context”). Count how often each happens and you get a ranked to-fix list for your app.",
    "Hamel's “Why is error analysis so important” FAQ",
    "Cluster notes into 5–8 named failure modes; count frequency",
    { doneWhen: "A ranked failure-mode table for your app", videoTitle: "Day 10: Failure modes ko group karo", projects: ["P2"], search: "LLM failure modes taxonomy error analysis" }),
  d(11, "Code checks before AI judges",
    "The cheapest, most reliable tests are plain code: does the output parse? Does it match the format? Did the right tool get called? Write these first — save the LLM judge for what code can't check.",
    "Eugene Yan on X: “don't neglect simple code-based evaluators such as checking for parsing structure, using regex, or executing tool calls”",
    "Write assertions for the failures a regex/parser CAN catch",
    { doneWhen: "≥3 deterministic checks run on the dataset", videoTitle: "Day 11: Pehle code se test karo, phir LLM se", projects: ["P2"], search: "code based evals LLM assertions regex" }),
  d(12, "LLM-as-judge — grading with a model",
    "For subjective failures (“is this answer grounded?”) you use a second model as the judge. The craft: one failure mode per judge, binary pass/fail, and always ask for its reasoning.",
    "Eugene Yan “Evaluating the Effectiveness of LLM-Evaluators” + Evidently LLM-as-judge guide",
    "Write a binary pass/fail judge prompt for ONE subjective failure mode",
    { doneWhen: "Judge returns pass/fail with reasoning on all traces", videoTitle: "Day 12: LLM judge ko insaan jitna accurate kaise banayein", projects: ["P2"], search: "LLM as judge tutorial pass fail" }),
  d(13, "Make the judge agree with you (Cohen's Kappa)",
    "A judge you haven't checked is just vibes. Compare its verdicts with your own labels, measure agreement with Cohen's Kappa, and tighten the prompt until the judge scores like you do.",
    "Eugene Yan “AlignEval” + Cohen's Kappa explainer (Han-Chung Lee)",
    "Measure judge-vs-your-labels agreement (Cohen's Kappa); iterate prompt until aligned",
    { doneWhen: "Kappa reported; judge agrees with you on a held-out set", videoTitle: "Day 13: Judge ko human ke saath align karo (Kappa)", projects: ["P2"], search: "align LLM judge human labels Cohen kappa" }),
  d(14, REST, REST_ABOUT,
    "Review week",
    "Write P2 README; showcase your failure-mode table",
    { doneWhen: "Aligned judge + failure taxonomy documented", videoTitle: "Day 14: Hafta 2 recap — judge kitna accurate nikla?", projects: ["P2"], isRest: true }),

  // ── Week 3 — Evals into CI, golden datasets, RAG eval (P2) ──────────────
  d(15, "Golden datasets — your quality yardstick",
    "A golden dataset is a small, hand-picked set of inputs with known expected behavior. Version it in the repo and every future change gets measured against the same yardstick.",
    "Hamel evals-faq (synthetic data section)",
    "Curate a 30-example golden set (inputs + expected behavior), incl. synthetic edge cases",
    { doneWhen: "Versioned golden.jsonl in repo", videoTitle: "Day 15: Golden dataset banao", projects: ["P2"], search: "golden dataset LLM evaluation build" }),
  d(16, "Eval frameworks — promptfoo in practice",
    "You've hand-rolled evals; now let a framework run them. Port your judge into promptfoo and get a pass/fail grid over the whole golden set with one command.",
    "promptfoo docs + DeepEval docs + Ragas docs",
    "Re-implement your judge as a promptfoo assert; run the golden set",
    { doneWhen: "promptfoo config runs and prints a pass grid", videoTitle: "Day 16: promptfoo se evals chalao", projects: ["P2"], search: "promptfoo tutorial LLM testing" }),
  d(17, "RAG metrics — the RAG triad",
    "Three questions diagnose any RAG failure: did we retrieve relevant context? Is the answer grounded in it? Does the answer address the question? Score all three and you know which stage to fix.",
    "DeepLearning.AI “Building and Evaluating Advanced RAG” (RAG triad: context relevance, groundedness, answer relevance) + Ragas faithfulness/context-precision",
    "Add faithfulness + context-precision metrics to P1 via Ragas or Phoenix",
    { doneWhen: "RAG triad scores computed on golden set", videoTitle: "Day 17: RAG ka triad — kya jawab sach hai?", projects: ["P2"], search: "RAG triad evaluation Ragas faithfulness" }),
  d(18, "Put evals in CI — block bad changes",
    "The payoff: a GitHub Action runs your evals on every pull request, and a change that makes quality worse fails with a red X — automatically, before it ships.",
    "Hamel evals-faq (CI) + promptfoo CI docs",
    "GitHub Action that runs evals on every PR and fails if pass-rate drops below threshold",
    { doneWhen: "Red X on a PR that regresses quality", videoTitle: "Day 18: CI mein eval gate lagao — regression pakdo", projects: ["P2"], search: "promptfoo CI GitHub Actions eval gate" }),
  d(19, "Evaluating agents — judge the path, not just the answer",
    "An agent can reach a right answer the wrong way (or luck into it). Trajectory evals check the steps — did it call the right tools, in a sensible order?",
    "DeepLearning.AI “Evaluating AI Agents” (Arize AI; John Gilhuly & Aman Khan)",
    "Add a trajectory/tool-call correctness check to a multi-step trace",
    { doneWhen: "Tool-call correctness measured on sample", videoTitle: "Day 19: Agent ki trajectory ko evaluate karo", projects: ["P2"], search: "evaluating AI agents trajectory tool calls" }),
  d(20, "The eval flywheel — a loop, not a chore",
    "Evals only pay off as a routine: review new traces weekly, label what's new, improve the app, repeat. Today you write that loop down as a real process with a schedule.",
    "Shreya Shankar “Data Flywheels for LLM Applications” + Eugene Yan “An LLM-as-Judge Won't Save The Product—Fixing Your Process Will”",
    "Document a weekly review→label→improve loop; set a cadence",
    { doneWhen: "A written flywheel SOP in the repo", videoTitle: "Day 20: Data flywheel — evals ko zinda rakho", projects: ["P2"], search: "data flywheel LLM applications" }),
  d(21, REST, REST_ABOUT,
    "Review week",
    "Ship P2 (eval harness + aligned judge + CI) as a portfolio piece",
    { doneWhen: "P2 is a standalone repo with README + CI badge", videoTitle: "Day 21: Hafta 3 recap — eval harness tayyar", projects: ["P2"], isRest: true }),

  // ── Week 4 — Context engineering + cost begin (P3) ──────────────────────
  d(22, "Context engineering — what the model actually sees",
    "Quality depends less on clever prompt wording and more on what fills the context window: system prompt, history, retrieved docs, tool outputs. Start by auditing what YOUR app sends — and what it wastes.",
    "Anthropic “Effective context engineering for AI agents” (Sep 29, 2025)",
    "Audit your P1 prompt; measure tokens per call; identify waste",
    { doneWhen: "Token budget table for your RAG", videoTitle: "Day 22: Context engineering — prompt nahi, context", projects: ["P3"], search: "context engineering AI agents Anthropic" }),
  d(23, "Context rot — why more context makes answers worse",
    "Stuffing the window hurts: models lose facts buried in the middle of long contexts. Measure your own accuracy-vs-tokens curve and find the sweet spot instead of guessing.",
    "Chroma “Context Rot” report + “Lost in the Middle” (TACL 2024)",
    "Test retrieval quality as you stuff more/less context; chart accuracy vs tokens",
    { doneWhen: "A chart showing the accuracy/token tradeoff", videoTitle: "Day 23: Zyada context = behtar? Nahi!", projects: ["P3"], search: "context rot lost in the middle LLM" }),
  d(24, "Prompt caching — same answers, less money",
    "If every call re-sends the same big prefix (system prompt, docs), the provider can cache it and charge a fraction. One of the easiest real cost wins — today you measure the actual savings.",
    "Anthropic prompt-caching docs",
    "Add prompt caching to repeated-prefix calls; measure $ saved",
    { doneWhen: "Before/after cost numbers logged", videoTitle: "Day 24: Prompt caching se paisa bachao", projects: ["P3"], search: "Anthropic prompt caching tutorial cost" }),
  d(25, "Compaction — keep long chats under budget",
    "Long conversations grow until they blow the window. Compaction summarizes older turns into a short recap so the chat stays sharp and under a token ceiling without losing the thread.",
    "Anthropic context-engineering post (compaction)",
    "Implement conversation compaction (summarize old turns) for a long chat",
    { doneWhen: "Long chat stays under a token ceiling", videoTitle: "Day 25: Purani baat ko compact karo", projects: ["P3"], search: "LLM conversation compaction summarization memory" }),
  d(26, "Model routing — cheap model when it's enough",
    "Not every query needs your biggest model. A router sends easy queries to a small cheap model and hard ones to the big one — often a huge cost cut at the same quality. Prove it with your evals.",
    "Anthropic “Building Effective Agents” (model selection) + OpenAI “A Practical Guide to Building Agents”",
    "Route easy queries to a small/cheap model, hard ones to a big model",
    { doneWhen: "Router cuts cost on a mixed workload", videoTitle: "Day 26: Sasta model kab, mehanga kab?", projects: ["P3"], search: "LLM model routing cost optimization" }),
  d(27, "See your spend — cost & latency dashboard",
    "You can't cut what you can't see. Attach cost and latency to every trace, then build the summary view that shows dollars and milliseconds per endpoint.",
    "Phoenix cost tracking",
    "Add per-request cost + latency to your traces; build a simple summary view",
    { doneWhen: "Dashboard shows $ and ms per endpoint", videoTitle: "Day 27: Cost aur latency ka dashboard", projects: ["P3"], search: "LLM cost tracking observability dashboard" }),
  d(28, REST, REST_ABOUT,
    "Review week",
    "Draft P3 “AI Reliability & Cost Audit” case study on your own RAG",
    { doneWhen: "P3 case study v1 with a real % cost reduction", videoTitle: "Day 28: Hafta 4 recap — kitna cost bacha?", projects: ["P3"], isRest: true }),

  // ── Week 5 — Memory, structured output, finish P3 ───────────────────────
  d(29, "Give the model a memory",
    "Chat models forget everything between sessions. A memory tool — even a simple file the model can read and write — lets it keep facts across conversations. Build the simplest version that works.",
    "Anthropic memory-tool docs / context-engineering post",
    "Add a file-based memory store (CRUD) to a chat agent",
    { doneWhen: "Agent recalls a fact across sessions", videoTitle: "Day 29: Agent ko yaad dilana sikhao", projects: ["P3", "P5"], search: "LLM agent memory tool persistent" }),
  d(30, "Structured output — JSON that never breaks",
    "Real systems need machine-readable output, not prose. Force the model to return JSON matching a schema, validate with Pydantic, and retry automatically when it doesn't parse.",
    "Pydantic docs + provider JSON-mode docs",
    "Force JSON output validated by Pydantic; handle parse failures",
    { doneWhen: "Invalid outputs are caught and retried", videoTitle: "Day 30: Structured output — JSON hamesha sahi", projects: ["P3"], search: "structured output LLM pydantic JSON mode" }),
  d(31, "Programmatic tool calling",
    "Instead of the model calling tools one at a time (each result flooding the context), let it write a small program that calls the tools and returns only the final answer. Context stays tiny.",
    "Anthropic context-engineering (programmatic tool calling)",
    "Let the model emit code that calls tools and returns only the final result",
    { doneWhen: "Context stays small on a multi-tool task", videoTitle: "Day 31: Tool ko code se call karo", projects: ["P3"], search: "programmatic tool calling code execution LLM" }),
  d(32, "Raise accuracy systematically — not by vibes",
    "Put the last three weeks together: use your golden set as the scoreboard and apply prompt, eval, and memory tuning until the pass rate measurably rises. Every change gets a number.",
    "DeepLearning.AI “Improving Accuracy of LLM Applications” (AMD/Meta)",
    "Apply prompt + eval + memory tuning to lift your golden-set pass rate",
    { doneWhen: "Documented accuracy gain vs baseline", videoTitle: "Day 32: Accuracy ko systematically barhao", projects: ["P2", "P3"], search: "improving accuracy LLM applications evals" }),
  d(33, "The audit methodology — your repeatable formula",
    "Turn everything from weeks 2–5 into a one-page checklist anyone can run on any LLM app: trace it, eval it, cut its cost, prove the quality. This checklist IS the service you can sell.",
    "Hamel evals-faq + your own P2/P3 work",
    "Write a repeatable “Reliability & Cost Audit” checklist (the productized-service spec)",
    { doneWhen: "A 1-page audit SOP anyone can follow", videoTitle: "Day 33: Reliability audit ka formula", projects: ["P3"], search: "AI reliability cost audit checklist LLM" }),
  d(34, "Turn the audit into a public case study",
    "Proof beats promises. Write up your own audit as a case study — the problem, the method, the % cost cut, the quality delta — in the exact format a future client would want to read.",
    "Freelance case-study blueprint (problem→approach→result)",
    "Turn P3 into a public case study: problem, method, % cost cut, quality delta",
    { doneWhen: "Publishable case study with metrics", videoTitle: "Day 34: Audit ko service banao", projects: ["P3"], search: "AI consulting case study write freelance" }),
  d(35, REST, REST_ABOUT,
    "Review",
    "Ship P3; post the case study; invite audits from Discord",
    { doneWhen: "P3 is a standalone case study others can copy", videoTitle: "Day 35: Hafta 5 recap — audit service live", projects: ["P3"], isRest: true }),

  // ── Week 6 — Agents from scratch (P4) ───────────────────────────────────
  d(36, "What an agent really is (and when NOT to build one)",
    "An agent is a model in a loop with tools, choosing its own next step. That freedom costs money and reliability — so the first skill is judging when a plain scripted workflow does the job better.",
    "Anthropic “Building Effective Agents” (workflows vs agents)",
    "Write the definition + a decision checklist: when NOT to build an agent",
    { doneWhen: "A README section arguing agent vs workflow", videoTitle: "Day 36: Agent ya workflow? Pehle socho", projects: ["P4"], search: "workflows vs agents Anthropic building effective agents" }),
  d(37, "The agent loop — a while loop and one tool",
    "Strip the mystery: an agent is think → act → observe, repeated until done. You'll write that loop in plain Python with a single tool and watch it solve a task no single prompt could.",
    "Victor Dibia “The Agent Execution Loop” + “Build an AI Agent from Scratch — No Frameworks” (DEV)",
    "Write a while-loop agent (think→act→observe) with ONE tool, no framework",
    { doneWhen: "Agent solves a task needing the tool", videoTitle: "Day 37: Agent loop — sirf Python aur while loop", projects: ["P4"], search: "build AI agent from scratch python no framework" }),
  d(38, "Tools — functions with schemas the model can trust",
    "A tool is a function plus a JSON schema that tells the model exactly how to call it. Good schemas and graceful error messages are what make an agent pick the right tool, reliably.",
    "Anthropic “Writing effective tools for AI agents”",
    "Add 3 tools with JSON schemas; handle tool errors gracefully",
    { doneWhen: "Agent picks the right tool for varied inputs", videoTitle: "Day 38: Tools likhna — agent ke liye, agent ke saath", projects: ["P4"], search: "LLM tool calling JSON schema tutorial" }),
  d(39, "Fewer, sharper tools",
    "Ten overlapping tools confuse a model more than three sharp ones. Consolidate (one good search_contacts beats list+filter+get) and namespace so every tool's job is obvious.",
    "Anthropic writing-tools post (namespacing, consolidation)",
    "Refactor tools: consolidate (e.g., search_contacts not list_contacts); namespace",
    { doneWhen: "Fewer, sharper tools; agent less confused", videoTitle: "Day 39: Kam tools, behtar tools", projects: ["P4"], search: "writing effective tools AI agents design" }),
  d(40, "When a plain workflow beats the agent",
    "Take a task your agent does and rebuild it as a fixed chain of prompts — no decisions, no loop. Compare cost and reliability. Knowing when NOT to use an agent is a superpower clients pay for.",
    "Anthropic “Building Effective Agents” (prompt chaining, routing)",
    "Build a deterministic workflow variant of a task; compare to the agent",
    { doneWhen: "Table: workflow vs agent on cost/reliability", videoTitle: "Day 40: Kabhi kabhi workflow hi kaafi hai", projects: ["P4"], search: "prompt chaining workflow LLM pattern" }),
  d(41, "Evaluate your agent with your own harness",
    "Your P2 eval harness meets your P4 agent: score the final answers AND the trajectories, and catch at least one real failure mode you didn't know it had.",
    "DeepLearning.AI “Evaluating AI Agents” (Arize) + your P2 harness",
    "Run trajectory + final-answer evals on the agent; catch a failure mode",
    { doneWhen: "Agent has its own eval suite", videoTitle: "Day 41: Apne agent ko test karo", projects: ["P4"], search: "AI agent evaluation tutorial" }),
  d(42, REST, REST_ABOUT,
    "Review",
    "Ship P4 (agent-from-scratch + tools + evals)",
    { doneWhen: "P4 standalone repo works and is evaluated", videoTitle: "Day 42: Hafta 6 recap — agent zinda hai", projects: ["P4"], isRest: true }),

  // ── Week 7 — Agent patterns & orchestration ─────────────────────────────
  d(43, "Evaluator–optimizer — the agent that fixes its own work",
    "One model generates, another critiques, the first revises. This generate → critique → revise loop measurably lifts quality on hard outputs — and you already know how to measure it.",
    "Anthropic “Building Effective Agents” (evaluator-optimizer)",
    "Add a generate→critique→revise loop to improve outputs",
    { doneWhen: "Quality improves over iterations, measured", videoTitle: "Day 43: Agent apni ghalti khud sudhare", search: "evaluator optimizer pattern LLM agents" }),
  d(44, "Orchestrator–workers — divide the work",
    "One model plans and splits the task; cheap worker calls execute the pieces; the orchestrator assembles the result. The go-to pattern when a task is too big for one context.",
    "Anthropic (orchestrator-workers pattern)",
    "Build an orchestrator that delegates subtasks to worker calls",
    { doneWhen: "Orchestrator completes a multi-part task", videoTitle: "Day 44: Orchestrator — kaam baant do", search: "orchestrator workers pattern AI agents" }),
  d(45, "Multi-agent — is it worth the token bill?",
    "Two agents (a doer and a verifier) catch more mistakes than one — but every extra agent multiplies cost. Measure both sides and learn to say exactly when multi-agent pays off.",
    "Anthropic multi-agent research write-up + “Building Effective Agents”",
    "Add a doer-verifier pair; measure token cost of multi-agent",
    { doneWhen: "You can state when multi-agent is worth it", videoTitle: "Day 45: Multi-agent — faida ya kharcha?", search: "multi agent LLM systems tradeoffs" }),
  d(46, "Human-in-the-loop — ask before the risky step",
    "Some actions can't be undone: sending the email, deleting the row, spending the money. Add an approval checkpoint so the agent pauses and asks a human before anything irreversible.",
    "Anthropic “human-agent teams” (verification, checkpoints)",
    "Add an approval checkpoint before an irreversible action",
    { doneWhen: "Agent pauses for human OK on risky steps", videoTitle: "Day 46: Khatarnak kaam se pehle insaan se pucho", search: "human in the loop AI agent approval checkpoint" }),
  d(47, "Guardrails — keep the agent in scope",
    "Guardrails are filters around the model: block bad inputs (injection, off-topic) and bad outputs (leaks, unsafe content) before they cause harm. Add your first input/output pair today.",
    "OpenAI “Practical Guide to Building Agents” (guardrails)",
    "Add input/output guardrails; block out-of-scope requests",
    { doneWhen: "Guardrail blocks a bad request in a demo", videoTitle: "Day 47: Agent pe guardrails lagao", search: "AI agent guardrails input output validation" }),
  d(48, "Framework literacy — see what they hide",
    "Now that you've built the loop yourself, rebuild it in a framework (smolagents or LangGraph) in a day. You'll instantly see what the framework automates — and what it hides from you.",
    "Hugging Face Agents Course (smolagents/LangGraph units)",
    "Rebuild your agent in one framework; note what it hides",
    { doneWhen: "You can map framework calls to your loop", videoTitle: "Day 48: Framework woh chhupata kya hai?", search: "smolagents LangGraph agent framework tutorial" }),
  d(49, REST, REST_ABOUT,
    "Review",
    "Consolidate agent patterns doc",
    { doneWhen: "Patterns cheatsheet in repo", videoTitle: "Day 49: Hafta 7 recap — patterns clear?", isRest: true }),

  // ── Week 8 — Long-horizon agents & harnesses (P5) ───────────────────────
  d(50, "The long-horizon problem — tasks bigger than one context",
    "Some tasks take hours and outlive any context window. The agent will 'forget' mid-task — so the system around it (the harness) must carry the memory. Today you design such a task and name the problem precisely.",
    "Anthropic “Effective harnesses for long-running agents” (Nov 26, 2025)",
    "Design a task that spans multiple context windows; document the memory problem",
    { doneWhen: "Written spec of a long-horizon task", videoTitle: "Day 50: Ghanton chalne wala agent — challenge kya hai", projects: ["P5"], search: "long running AI agents harness" }),
  d(51, "External state — the agent's notebook",
    "The fix for forgetting: a durable state file (a to-do list, progress notes) the agent reads at the start of every session and updates before it ends. Kill the process, restart it, and watch it resume.",
    "Anthropic harnesses post (session state)",
    "Give the agent a durable to-do/state file it reads at each session start",
    { doneWhen: "Agent resumes work after a “restart”", videoTitle: "Day 51: Har session yaad rakhe kaam kahan tha", projects: ["P5"], search: "AI agent state persistence resume task" }),
  d(52, "Verify before moving on",
    "Long runs compound errors: one bad step poisons everything after it. Make the agent verify its own work (run the tests, check the rubric) before each handoff to the next cycle.",
    "Anthropic harnesses post (doer-verifier)",
    "Add self-verification (tests/rubrics) before handoff",
    { doneWhen: "Agent verifies its own work each cycle", videoTitle: "Day 52: Kaam check karke aage barho", projects: ["P5"], search: "AI agent self verification doer verifier" }),
  d(53, "Reflection — learn from your own misses",
    "Add a step where the agent reviews what went wrong in past cycles and adjusts its approach. Logged across runs, you can literally watch it get better at the task.",
    "Anthropic harnesses + human-agent teams (reflection)",
    "Add a reflection step that reviews past misses and adjusts",
    { doneWhen: "Agent improves across runs, logged", videoTitle: "Day 53: Agent apni misses se seekhe", projects: ["P5"], search: "AI agent reflection self correction" }),
  d(54, "Cost control on long runs",
    "An unattended agent can burn real money. Give it context-awareness (how much budget remains) plus compaction, and enforce a hard token/dollar cap the run can never cross.",
    "Anthropic context-awareness/compaction",
    "Add context-awareness (remaining budget) + compaction to the long-horizon agent",
    { doneWhen: "Long run stays under a hard token/$ cap", videoTitle: "Day 54: Lambe run mein paisa control", projects: ["P5", "P3"], search: "LLM agent token budget cost control" }),
  d(55, "Evaluate the whole long run",
    "Judge the marathon, not a lap: run your long-horizon agent through a full multi-session task and score it end-to-end with your P2 harness — pass/fail on the real goal.",
    "Your P2 harness + trajectory evals",
    "Evaluate the long-horizon agent over a full multi-session task",
    { doneWhen: "Pass/fail on a realistic long task", videoTitle: "Day 55: Poore lambe task ko evaluate karo", projects: ["P5"], search: "evaluating long horizon AI agents" }),
  d(56, REST, REST_ABOUT,
    "Review",
    "Ship P5 (long-horizon agent + memory + harness)",
    { doneWhen: "P5 standalone, resumes across sessions", videoTitle: "Day 56: Hafta 8 recap — long-horizon agent tayyar", projects: ["P5"], isRest: true }),

  // ── Week 9 — Buffer, tasters, mid-challenge case study ──────────────────
  d(57, "Computer use — agents that drive a screen",
    "A taster day: models can now look at a screen, move the mouse, and type. Run a sandboxed demo, see what it can do, and note exactly why the sandbox (safety limits) matters.",
    "DeepLearning.AI “Building toward Computer Use with Anthropic”",
    "Run a sandboxed computer-use demo; note safety limits",
    { doneWhen: "A recorded computer-use demo", videoTitle: "Day 57: Computer use — agent screen chalaye", search: "Claude computer use agent demo" }),
  d(58, "Voice agents — give your agent a voice",
    "A taster day: speech-to-text in, text-to-speech out, wrapped around the agent you already have. One integration pattern, one working demo.",
    "DeepLearning.AI “Voice for AI Agents and Applications” (Vocal Bridge)",
    "Add a voice layer to an existing agent (one integration pattern)",
    { doneWhen: "Voice in/out works on a demo", videoTitle: "Day 58: Apne agent ko awaaz do", search: "voice AI agent tutorial speech" }),
  d(59, "Tests make it real",
    "A buffer day with compounding returns: add pytest coverage to your two strongest projects. Tests passing in CI is what separates a portfolio piece from a script.",
    "pytest docs",
    "Add tests to your two strongest projects",
    { doneWhen: "Tests pass in CI", videoTitle: "Day 59: Code ko test se mazboot karo", search: "pytest tutorial python testing basics" }),
  d(60, "Mid-challenge case study — the halfway proof",
    "Write the public 'Days 1–59: what I built' post with real metrics. Half the challenge done deserves proof — and the writing habit is exactly what lands clients later.",
    "Freelance case-study blueprint",
    "Write a “Days 1–59: what I built” case study with metrics",
    { doneWhen: "Public mid-point case study", videoTitle: "Day 60: Aadha challenge — kya seekha", search: "build in public developer case study" }),
  d(61, "MCP — the problem it solves",
    "Every AI app × every data source = a mess of custom integrations (M×N). The Model Context Protocol is the USB-C moment: one standard plug between models and tools. Understand the why before the how.",
    "Hugging Face MCP Course Unit 1 (M×N integration problem)",
    "Diagram how MCP replaces custom integrations",
    { doneWhen: "A clear MCP explainer in your words", videoTitle: "Day 61: MCP kya hai aur kyun zaroori", search: "model context protocol MCP explained" }),
  d(62, "MCP architecture — clients, servers, and what they exchange",
    "Map the moving parts: hosts and clients on one side, servers on the other, exchanging tools (actions), resources (data), and prompts (templates). After today you can label every piece.",
    "HF MCP Course Unit 1–2 + DeepLearning.AI “MCP: Build Rich-Context AI Apps with Anthropic” (Elie Schoppik)",
    "Map client/server/tools/resources/prompts of MCP",
    { doneWhen: "You can label every MCP component", videoTitle: "Day 62: MCP ka architecture kholo", search: "MCP architecture tools resources prompts" }),
  d(63, REST, REST_ABOUT,
    "Review",
    "Consolidate; plan the MCP build",
    { doneWhen: "MCP plan documented", videoTitle: "Day 63: Hafta 9 recap — MCP se pehle", isRest: true }),

  // ── Week 10 — Build an MCP server (P6) ──────────────────────────────────
  d(64, "Hand-build a real database first",
    "Your MCP server needs something real to expose. Design and seed a small SQLite database (a bookstore, an inventory — something with real rows) that you understand completely.",
    "SQLite docs",
    "Design + seed a small real DB (e.g., a bookstore/inventory)",
    { doneWhen: "Queryable local DB with real data", videoTitle: "Day 64: Apna database khud banao", projects: ["P6"], search: "SQLite python tutorial create database" }),
  d(65, "Your first MCP server",
    "The big moment: expose ONE tool — query the database — through an MCP server, and watch an MCP client discover and call it. Small scope on purpose; the plumbing is the lesson.",
    "HF MCP Course Unit 2 (SDK) + FastMCP",
    "Expose ONE tool (query the DB) via an MCP server",
    { doneWhen: "An MCP client can call your tool", videoTitle: "Day 65: Pehla MCP server — DB pe tool", projects: ["P6"], search: "build MCP server FastMCP tutorial" }),
  d(66, "MCP resources & prompts",
    "Tools act; resources are read-only data the client can browse; prompts are reusable templates the server offers. Add one of each and see how they show up differently in the client.",
    "HF MCP Course Unit 2",
    "Add MCP resources (read-only data) and a prompt template",
    { doneWhen: "Client sees resources + prompt", videoTitle: "Day 66: MCP resources aur prompts", projects: ["P6"], search: "MCP server resources prompts tutorial" }),
  d(67, "One server, many tools — kept clean",
    "Grow the server to search/create/update — applying the Day 39 lesson: consolidated, namespaced tools an agent can't confuse. Then let your own agent drive the whole thing.",
    "Anthropic writing-tools (namespacing)",
    "Add search/create/update tools; namespace them",
    { doneWhen: "Agent uses your MCP server end-to-end", videoTitle: "Day 67: Ek server, kai tools", projects: ["P6"], search: "MCP server multiple tools design" }),
  d(68, "Plug into a real client",
    "Wire your server into Claude Desktop (or another MCP-capable app) and watch a production client you didn't write drive your database. That's the whole point of a protocol.",
    "HF MCP Course Unit 3",
    "Wire your server into Claude Desktop / an MCP-capable client",
    { doneWhen: "Real client drives your DB via MCP", videoTitle: "Day 68: Asli client se MCP jodo", projects: ["P6"], search: "connect MCP server Claude Desktop" }),
  d(69, "Evaluate the MCP tools",
    "Same discipline, new surface: generate realistic tasks and measure whether the model picks the right tool with the right arguments. Tool-selection accuracy is an evalable number.",
    "Anthropic tool-evaluation cookbook",
    "Generate eval tasks; measure tool-selection accuracy",
    { doneWhen: "Tool-use eval report", videoTitle: "Day 69: MCP tools ko test karo", projects: ["P6"], search: "evaluating LLM tool use accuracy" }),
  d(70, REST, REST_ABOUT,
    "Review",
    "Ship P6 (MCP server over hand-built DB)",
    { doneWhen: "P6 standalone, works with a real client", videoTitle: "Day 70: Hafta 10 recap — MCP server live", projects: ["P6"], isRest: true }),

  // ── Week 11 — Retrieval depth (P7) ──────────────────────────────────────
  d(71, "Keyword vs semantic search",
    "Vectors miss exact terms (error codes, names); keywords miss paraphrases. BM25 and embeddings fail on different queries — run both on the same corpus and see it with your own eyes.",
    "DeepLearning.AI “Retrieval Augmented Generation (RAG)” (search techniques)",
    "Add BM25 keyword search alongside your vector search",
    { doneWhen: "Both retrievers run on the same corpus", videoTitle: "Day 71: Keyword vs semantic search", projects: ["P7"], search: "BM25 vs vector search RAG" }),
  d(72, "Hybrid search — fuse both rankings",
    "Combine keyword and vector results with Reciprocal Rank Fusion: an item both retrievers like rises to the top. Done right, hybrid beats either alone — your eval will prove it.",
    "pguso/rag-from-scratch (RRF, weighted fusion)",
    "Combine BM25 + vectors with Reciprocal Rank Fusion",
    { doneWhen: "Hybrid beats either alone on your eval", videoTitle: "Day 72: Hybrid search — dono ka faida", projects: ["P7"], search: "hybrid search reciprocal rank fusion RAG" }),
  d(73, "Query rewriting — fix the question, not the index",
    "Users don't speak in your documents' vocabulary. Multi-query expansion (ask it 3 ways) and HyDE (embed a hypothetical answer) bridge that gap and rescue hard queries.",
    "Dataquest “Build a RAG from Scratch” (multi-query, HyDE) + rag-from-scratch query-rewriting",
    "Add multi-query expansion; test on vocabulary-gap queries",
    { doneWhen: "Recall improves on hard queries", videoTitle: "Day 73: Query ko behtar likho (multi-query, HyDE)", projects: ["P7"], search: "query expansion multi query HyDE RAG" }),
  d(74, "Reranking — put the best chunk on top",
    "Retrieval gets you 20 candidates fast; a reranker reads each one carefully and reorders them so the truly best chunks fill your small context budget. Measure the precision lift.",
    "Dataquest RAG post (Cohere Rerank) + open reranker",
    "Add a reranking stage; measure precision lift",
    { doneWhen: "Rerank improves top-k precision", videoTitle: "Day 74: Reranking — behtareen chunk upar", projects: ["P7"], search: "reranking RAG cross encoder rerank" }),
  d(75, "Contextual retrieval — chunks that carry their context",
    "A chunk saying 'the company grew 3%' is useless without knowing which company, which quarter. Prepend that context to every chunk before embedding (Anthropic's method) and watch retrieval jump.",
    "Anthropic “Contextual Retrieval”",
    "Add context to chunks before embedding; measure retrieval gain",
    { doneWhen: "Contextual chunks beat naive chunks", videoTitle: "Day 75: Chunk ko context do", projects: ["P7"], search: "Anthropic contextual retrieval explained" }),
  d(76, "Retrieval metrics done right",
    "Score retrieval itself, separately from generation: recall@k (did the right chunk make the list?), MRR (how high?), context precision (how much junk came along?). On your golden queries.",
    "Hamel evals-faq (similarity metrics for retrieval) + Ragas context metrics",
    "Build a retrieval eval: recall@k, MRR, context-precision",
    { doneWhen: "Retrieval scored on golden queries", videoTitle: "Day 76: Retrieval ko sahi metric se naapo", projects: ["P7"], search: "retrieval evaluation recall MRR context precision" }),
  d(77, REST, REST_ABOUT,
    "Review",
    "Ship P7 (hybrid-search retrieval engine)",
    { doneWhen: "P7 standalone with a metrics report", videoTitle: "Day 77: Hafta 11 recap — retrieval engine tayyar", projects: ["P7"], isRest: true }),

  // ── Week 12 — AI security & red-teaming (P8) ────────────────────────────
  d(78, "OWASP LLM Top 10 — know the risks by name",
    "The industry's standard list of what goes wrong in LLM apps — prompt injection, data leakage, excessive agency and more. Map each risk to YOUR apps and you have a real risk register.",
    "OWASP Top 10 for LLM Applications (2025)",
    "Map each risk to your own P1/P4 apps",
    { doneWhen: "A risk register for your apps", videoTitle: "Day 78: OWASP LLM Top 10 — apne app pe", projects: ["P8"], search: "OWASP top 10 LLM applications explained" }),
  d(79, "Prompt injection — break your own app",
    "The #1 LLM vulnerability: text in the input (or in a retrieved document!) that hijacks the model's instructions. Today you attack your own RAG and document every injection that works.",
    "OWASP LLM01 + DeepLearning.AI “Red Teaming LLM Applications” (Giskard)",
    "Craft injections that break your RAG; document each",
    { doneWhen: "≥3 working injections on your app", videoTitle: "Day 79: Prompt injection — apne app ko toro", projects: ["P8"], search: "prompt injection attack examples RAG" }),
  d(80, "Agentic threats — when the agent itself is the risk",
    "Agents add new attack surface: goal hijacking, tool misuse, memory poisoning. Threat-model your own P4/P5 agents against the OWASP agentic list, risk by risk.",
    "OWASP “Top 10 for Agentic Applications” (Dec 9, 2025): goal hijack, tool misuse, memory poisoning",
    "Threat-model your agent (P4/P5) against ASI01–ASI10",
    { doneWhen: "Agentic threat model documented", videoTitle: "Day 80: Agentic Top 10 — naye khatre", projects: ["P8"], search: "OWASP agentic AI top 10 threats" }),
  d(81, "Automated scanning with garak",
    "Manual attacks don't scale. garak fires 120+ probe types at your endpoint automatically. Run it, then do the analyst's job: triage the findings into real vs noise, prioritized.",
    "garak docs (NVIDIA, 120+ probes)",
    "Run garak against your LLM endpoint; triage findings",
    { doneWhen: "garak report with prioritized issues", videoTitle: "Day 81: garak se scan karo", projects: ["P8"], search: "garak LLM vulnerability scanner tutorial" }),
  d(82, "Red-teaming in CI",
    "Security as a regression test: promptfoo's red-team plugins (jailbreak, PII, hijacking) run on every PR, so a change that opens a hole gets a red X before it ships.",
    "promptfoo redteam docs (plugins: jailbreak, pii, hijacking; OWASP preset)",
    "Add a promptfoo redteam config to CI; block on new vulns",
    { doneWhen: "Red-team gate runs on PRs", videoTitle: "Day 82: promptfoo redteam CI mein", projects: ["P8"], search: "promptfoo red team LLM security CI" }),
  d(83, "Multi-turn attacks with PyRIT",
    "Real attackers don't ask once — they escalate over many turns (Crescendo). Microsoft's PyRIT automates these conversations and finds what single-shot scanners can't see.",
    "PyRIT docs (Crescendo, TAP)",
    "Run a multi-turn crescendo attack; see what single-shot scans miss",
    { doneWhen: "A multi-turn exploit documented", videoTitle: "Day 83: PyRIT — multi-turn crescendo attack", projects: ["P8"], search: "PyRIT crescendo multi turn attack LLM" }),
  d(84, REST, REST_ABOUT,
    "Review",
    "Draft the guardrails kit design",
    { doneWhen: "Guardrails plan documented", videoTitle: "Day 84: Hafta 12 recap — kitne holes mile?", projects: ["P8"], isRest: true }),

  // ── Week 13 — Guardrails, defense, ship P8 ──────────────────────────────
  d(85, "Guardrails that stop your own attacks",
    "Now switch sides. Build input filters and output validators — and the bar is concrete: they must block the actual attacks you wrote on Days 79–83. Defense measured against real offense.",
    "OpenAI Practical Guide (guardrails) + OWASP mitigations",
    "Build input filters + output validators for injection/PII",
    { doneWhen: "Guardrails block your Day 79–83 attacks", videoTitle: "Day 85: Guardrails jo attacks rok dein", projects: ["P8"], search: "LLM guardrails prompt injection defense" }),
  d(86, "Least privilege — the agent gets only what it needs",
    "The best defense against tool misuse is an agent that CAN'T do the damage: restrict tool scopes, require approvals for risky calls, deny by default. Excessive agency is a choice — don't make it.",
    "OWASP Agentic (excessive agency, ASI mitigations)",
    "Restrict agent tool scopes; add least-privilege + approval",
    { doneWhen: "Agent can't do out-of-scope actions", videoTitle: "Day 86: Agent ko sirf itni azaadi", projects: ["P8"], search: "AI agent least privilege excessive agency" }),
  d(87, "Security regression — fixed stays fixed",
    "Every vulnerability you fixed becomes a permanent test in CI. Six months from now, nobody can accidentally reopen the hole without the pipeline turning red.",
    "promptfoo redteam + your CI",
    "Add security regression tests so fixed vulns stay fixed",
    { doneWhen: "Security suite green in CI", videoTitle: "Day 87: Security regression gate", projects: ["P8"], search: "security regression testing LLM CI" }),
  d(88, "The security audit case study",
    "Write up the whole arc — found X vulnerabilities, built Y guardrails, proved it in CI — as a publishable case study. 'I red-teamed and hardened my own app' is a rare, hireable sentence.",
    "Freelance case-study blueprint",
    "Write a red-team + guardrails case study (found X, fixed Y)",
    { doneWhen: "Publishable security case study", videoTitle: "Day 88: Security audit case study", projects: ["P8"], search: "AI security audit case study red team" }),
  d(89, "Ship P8 — the red-team + guardrails kit",
    "Package the attacks, the guardrails, and the CI config into one reusable repo you can point at ANY LLM app. This kit is a service offering disguised as a portfolio piece.",
    "Review",
    "Package red-team + guardrails kit as a reusable repo",
    { doneWhen: "P8 standalone, reusable on any LLM app", videoTitle: "Day 89: Red-team + guardrails kit live", projects: ["P8"], search: "LLM red team guardrails toolkit" }),
  d(90, "Capstone spec — scope one system that combines it all",
    "Plan the finale: ONE polished system using retrieval, an agent, evals, and security together. The discipline is scoping — write the spec and the done-when before any code.",
    "Anthropic “Building Effective Agents” (start simple)",
    "Scope ONE polished capstone combining RAG+agent+evals+security",
    { doneWhen: "Written capstone spec + done-when", videoTitle: "Day 90: Capstone plan — sab kuch jodo", projects: ["CAP"], search: "AI capstone project plan scope" }),
  d(91, REST, REST_ABOUT,
    "Review",
    "Kickoff capstone build; recruit Discord feedback",
    { doneWhen: "Capstone repo scaffolded", videoTitle: "Day 91: Hafta 13 recap — capstone shuru", projects: ["CAP"], isRest: true }),

  // ── Week 14 — Capstone + client-acquisition sprint (CAP) ────────────────
  d(92, "Capstone build I — the core path",
    "Heads-down building: retrieval plus the agent loop, the spine of your capstone. Get the happy path working end-to-end before touching anything fancy.",
    "Your own stack",
    "Build core: retrieval + agent loop",
    { doneWhen: "Core capstone path works", videoTitle: "Day 92: Capstone build — core tayyar", projects: ["CAP"], search: "build RAG agent application project" }),
  d(93, "Capstone build II — wire in the evals",
    "Your capstone gets what every project got: a golden set, judges, and a CI gate. From today, the capstone can't silently get worse.",
    "Your P2 harness",
    "Add eval suite + CI gate to capstone",
    { doneWhen: "Capstone has passing evals", videoTitle: "Day 93: Capstone pe evals lagao", projects: ["CAP"], search: "LLM app eval suite CI pipeline" }),
  d(94, "Capstone build III — harden it",
    "Point your own P8 kit at your own capstone: guardrails on, red-team pass run. Shipping something that survives your best attacks is the standard now.",
    "Your P8 kit",
    "Add guardrails + a red-team pass",
    { doneWhen: "Capstone survives your own red-team", videoTitle: "Day 94: Capstone ko secure karo", projects: ["CAP"], search: "secure LLM application guardrails red team" }),
  d(95, "Portfolio — make the 100 days visible",
    "Assemble everything — 8 projects plus capstone — into one index a stranger can skim in two minutes: what each thing is, what it proves, with metrics. This page IS your resume now.",
    "Freelance case-study blueprint (problem→approach→result→metrics)",
    "Assemble all 8 projects + capstone into a portfolio site/README index",
    { doneWhen: "Portfolio index live with metrics", videoTitle: "Day 95: Portfolio banao — 8 projects", projects: ["CAP"], search: "AI engineer portfolio examples projects" }),
  d(96, "Reposition your profiles around the niche",
    "Generic 'AI developer' profiles compete with everyone. Rewrite Upwork and LinkedIn around the specific thing you now demonstrably do: AI reliability & cost audits, with proof.",
    "Freelance positioning patterns (specialize; “use case” story posts)",
    "Rewrite Upwork profile + LinkedIn around “AI Reliability & Cost Audit”; add a specialized profile",
    { doneWhen: "Profiles repositioned to the niche", videoTitle: "Day 96: Upwork profile ko reposition karo", projects: ["CAP"], search: "freelance positioning niche upwork profile" }),
  d(97, "The productized audit offer",
    "Turn the audit SOP into a fixed-scope, fixed-price offer: deliverables, timeline, price band, on one public page. Productized means a client can say yes without a discovery call.",
    "Your P3 audit SOP",
    "Publish a fixed-scope “AI Reliability & Cost Audit” offer (deliverables, price band)",
    { doneWhen: "A public one-page audit offer", videoTitle: "Day 97: Audit offer — scope, fixed price", projects: ["CAP"], search: "productized service offer freelance consulting" }),
  d(98, REST, REST_ABOUT,
    "Review",
    "Community showcase of capstones; peer feedback",
    { doneWhen: "Capstone demo recorded", videoTitle: "Day 98: Hafta 14 recap — capstone demos", projects: ["CAP"], isRest: true }),
  d(99, "Outreach — turn the work into conversations",
    "Content brings inbound; outreach brings it faster. Turn your 100 days into three client-facing posts and send ten warm, specific messages to people who have the problem you now solve.",
    "Build-in-public + LinkedIn “use case” posts",
    "Turn the 100 days into 3 client-facing posts; send warm outreach to 10 targets",
    { doneWhen: "10 outreach messages sent; posts live", videoTitle: "Day 99: Funnel — content ko client mein badlo", projects: ["CAP"], search: "freelance client outreach warm messages" }),
  d(100, "Ship everything + retrospective",
    "The last day: publish the capstone case study, write what 100 days taught you, and announce that the audit offer is open. Then rest — you've built a career's foundation in 100 days.",
    "—",
    "Publish final capstone case study; write a “what 100 days taught me” post; announce audit availability",
    { doneWhen: "Everything public; offer live", videoTitle: "Day 100: Challenge complete — kaam public", projects: ["CAP"], search: "100 days of code retrospective lessons" }),
];

export const MODERN_AI_2026: Challenge = {
  id: "modern-ai-2026",
  title: "100 Days of Modern AI",
  totalDays: 100,
  cohortStart: COHORT_START_DATE,
  github: GITHUB_REPO,
  creator: CREATOR,
  days: DAYS.map((day) => ({
    ...day,
    ...(VIDEOS[day.day] ? { video: VIDEOS[day.day] } : {}),
    ...(OWNER_NOTES[day.day] ? { ownerNote: OWNER_NOTES[day.day] } : {}),
    ...(WATCH_LINKS[day.day] ? { watchLinks: WATCH_LINKS[day.day] } : {}),
    ...(QUIZZES[day.day] ? { quiz: QUIZZES[day.day] } : {}),
  })),
  weeks: WEEKS,
  projects: PROJECTS,
  courses: COURSES,
};
